---

version: "3.8"

services:

  consumer:
    image: tonyskidmore/consumer:0.0.1
    networks:
      - test
    environment:
      RABBIT_HOST: rabbitmq-01
      RABBIT_PORT: 5672
      RABBIT_USERNAME: guest
      RABBIT_PASSWORD: guest

networks:
  test:
    external: true

      
