---

version: "3.8"

services:
  consul:
    image: consul:1.7.9
    hostname: "{{.Node.Hostname}}"
    networks:
      - consul
      - test
    ports:
      - 8400:8400
      - 8500:8500
      - 8600:8600
    volumes:
      - consul-data:/consul/data
    deploy:
      mode: global
      # placement:
      #  constraints: [node.labels.consul == true]
    command: [ "agent", "-server", "-bootstrap-expect=3", "-retry-max=3", "-retry-interval=10s", "-datacenter=dc1", "-join=consul", "-retry-join=consul", "-bind={{ GetInterfaceIP \"eth0\" }}", "-client=0.0.0.0", "-ui"]

networks:
  consul:
  test:
    external: true

volumes:
  consul-data:
