{
 "title": "Runtime Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Application Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Customer Sessions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(StockManagement_SessionStatus) without(host, instance, job)"
    }
   ]
  },
  {
   "title": "Stock Orders",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 1 },
   "targets": [
    {
     "expr": "sum(StockManagement_SessionStatus{status=\"order-submitted\"})"
    }
   ]
  },
  { "title": "Runtime Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "JVM Thread Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_threads_current", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "JVM Heap Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used{area=\"heap\"}) without(instance, job)"
    }
   ]
  },
  {
   "title": "Tomcat requests/sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(tomcat_requestprocessor_request_count{name=\"http-nio-8080\"}[12h])) without (host, instance, job)"
    }
   ]
  },
  {
   "title": "Docker Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true
  },
  {
   "title": "Nodes Online",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 19 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(swarm_manager_nodes{state=\"ready\"})"
    }
   ]
  },
  {
   "title": "Container states",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 3, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(engine_daemon_container_states_containers) without(instance, job)"
    }
   ]
  },
  {
   "title": "Running containers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(engine_daemon_container_states_containers{state=\"running\"}) without (job, state)"
    }
   ]
  },
  {
   "title": "Failed Healthchecks",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(engine_daemon_health_checks_failed_total) without(job)"
    }
   ]
  },
  {
   "title": "Nodes Offline",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 22 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(swarm_manager_nodes{state!=\"ready\"})"
    }
   ]
  }
 ]
}